language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  - sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
  - ./utils/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  
script:
  - source .envrc
  - travis_wait run-project

notifications:
  email:
     on_success: change
     on_failure: change 
