name: teaching_microeconometrics

channels:
- conda
- conda-forge
- r

dependencies:
- numpy
- pandas
- flake8
- pytest
- scipy=1.2.1
- jupyterlab
- matplotlib
- seaborn
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- pip
- pygraphviz
- rise
- r-essentials
- rpy2
- simplegeneric
- pip:
      - wbdata  
