name: ose-course-data-science

channels:
- defaults
- conda-forge
- opensourceeconomics
- r

dependencies:
- numpy
- libgfortran
- pandas
- sphinx>=1.4
- numba==0.48.0
- linearmodels
- respy
- flake8
- pytest==5.4.3
- pytest-black
- pytest-flake8
- scipy
- jupyterlab
- matplotlib
- seaborn==0.10.1
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- ipython
- ipykernel
- pip
- pygraphviz
- rise
- r-essentials
- r-icc
- libiconv
- rpy2
- xlrd
- nbsphinx
- simplegeneric
- nb_black
- nbdime
- scikit-learn
- chaospy
- estimagic
- parso>=0.8.0
- pre-commit
- pip:
    - black-nb
    - flake8-nb
    - linearmodels
    - openpyxl
    - black==19.10b0
    - scikit-learn
    - sphinx_rtd_theme
    - nbsphinx
    - cairosvg
    - sphinxcontrib-bibtex
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
    - grmpy
