name: teaching-microeconometrics

channels:
- defaults
- conda-forge
- opensourceeconomics
- r

dependencies:
- numpy
- libgfortran
- pandas
- sphinx>=1.4
- numba
- respy
- flake8
- pytest
- pytest-black
- pytest-flake8
- black
- scipy
- jupyterlab
- matplotlib
- seaborn
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- ipython
- ipykernel
- pip
- pygraphviz
- rise
- r-essentials
- r-icc
- libiconv
- rpy2
- xlrd
- nbsphinx
- simplegeneric
- nb_black
- nbdime
- scikit-learn
- chaospy
- estimagic
- pip:
    - black-nb
    - flake8-nb
    - linearmodels
    - openpyxl
    - scikit-learn
    - sphinx_rtd_theme
    - nbsphinx
    - cairosvg
    - sphinxcontrib-bibtex
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
    - grmpy
