name: hc_microeconometrics

channels:
- conda
- conda-forge

dependencies:
- numpy
- pandas
- flake8
- pytest
- pandas 
- jupyterlab
- matplotlib
- seaborn
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- pip
- pip:
      - wbdata  
