name: teaching-microeconometrics

channels:
- defaults
- conda-forge
- r

dependencies:
- numpy
- libgfortran 
- pandas
- flake8
- pytest
- pytest-black 
- black
- scipy
- jupyterlab
- matplotlib
- seaborn
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- pip
- pygraphviz
- rise
- r-essentials
- r-icc
- libiconv 
- rpy2
- simplegeneric
- pip:
    - linearmodels
