name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04.

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
           activate-environment: ose-course-data-science
           environment-file: environment.yml
           python-version: 3.7
           auto-activate-base: false
    - name: Pytest and submodule
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        git submodule update --init --recursive
        py.test
    - name: check notebook formatting
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        flake8-nb; [ $? -eq 0 ] || exit 1
        black-nb --check .; [ $? -eq 0 ] || exit 1
    - name: run project
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        run-project
    - name: execute selected scripts
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        cd problem-sets/potential-outcome-model/data; python data-generation.py; cd $PROJECT_ROOT
        cd problem-sets/regression-discontinuity-design; python auxiliary.py; cd $PROJECT_ROOT
        cd lectures/mechanisms-causal-explanation/material; python run_respy.py; cd $PROJECT_ROOT
        cd figures; jupyter nbconvert --to html --execute figures.ipynb; cd $PROJECT_ROOT
